version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sde-events-support-service
    restart: unless-stopped
    ports:
      - "${PORT:-3001}:3001"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3001}
      - SDE_API_URL=${SDE_API_URL:-https://api.sde.globoi.com}
      - SDE_API_TOKEN=${SDE_API_TOKEN}
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "node", "-e", "require('http').get('http://localhost:3001/healthcheck', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sde-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  sde-network:
    driver: bridge
