version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sde-events-support-service-dev
    restart: unless-stopped
    ports:
      - "${PORT:-3001}:3001"
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-3001}
      - SDE_API_URL=${SDE_API_URL:-https://api.sde.globoi.com}
      - SDE_API_TOKEN=${SDE_API_TOKEN}
    env_file:
      - .env
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./package-lock.json:/app/package-lock.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - /app/node_modules
    networks:
      - sde-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: npm run dev

networks:
  sde-network:
    driver: bridge
